using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ITHunterview.Service.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class UpdateCompanyStatusEnum : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:Enum:activity_log_category", "auth,system,data_mutation,security")
                .Annotation("Npgsql:Enum:activity_log_status", "success,fail")
                .Annotation("Npgsql:Enum:application_status", "applied,viewed,shortlisted,interviewing,offered,hired,rejected,withdrawn")
                .Annotation("Npgsql:Enum:company_status", "draft,pending,verified,rejected")
                .Annotation("Npgsql:Enum:company_verification_method", "business_registration,poa_and_id")
                .Annotation("Npgsql:Enum:credit_transaction_type", "topup,deduct,refund,bonus")
                .Annotation("Npgsql:Enum:difficulty_level", "easy,medium,hard")
                .Annotation("Npgsql:Enum:email_log_status", "sent,failed,pending")
                .Annotation("Npgsql:Enum:employment_type", "full_time,part_time,contract,freelance")
                .Annotation("Npgsql:Enum:interview_session_status", "in_progress,completed,cancelled")
                .Annotation("Npgsql:Enum:job_status", "draft,pending_review,published,rejected,expired,closed")
                .Annotation("Npgsql:Enum:job_type", "full_time,part_time,contract,freelance,internship")
                .Annotation("Npgsql:Enum:notification_type", "system,application,interview,payment,promotion")
                .Annotation("Npgsql:Enum:payment_gateway", "vnpay,momo,stripe,paypal,bank_transfer")
                .Annotation("Npgsql:Enum:payment_status", "pending,success,failed,refunded")
                .Annotation("Npgsql:Enum:payment_target_type", "subscription,wallet_topup,job_promotion")
                .Annotation("Npgsql:Enum:promotion_status", "active,expired,cancelled")
                .Annotation("Npgsql:Enum:review_status", "pending,approved,rejected")
                .Annotation("Npgsql:Enum:skill_status", "active,deactive")
                .Annotation("Npgsql:Enum:subscription_status", "active,inactive")
                .Annotation("Npgsql:Enum:user_status", "active,inactive,banned,pending_verification")
                .Annotation("Npgsql:Enum:user_subscription_status", "active,expired,cancelled")
                .OldAnnotation("Npgsql:Enum:activity_log_category", "auth,system,data_mutation,security")
                .OldAnnotation("Npgsql:Enum:activity_log_status", "success,fail")
                .OldAnnotation("Npgsql:Enum:application_status", "applied,viewed,shortlisted,interviewing,offered,hired,rejected,withdrawn")
                .OldAnnotation("Npgsql:Enum:company_status", "pending,verified,rejected")
                .OldAnnotation("Npgsql:Enum:company_verification_method", "business_registration,poa_and_id")
                .OldAnnotation("Npgsql:Enum:credit_transaction_type", "topup,deduct,refund,bonus")
                .OldAnnotation("Npgsql:Enum:difficulty_level", "easy,medium,hard")
                .OldAnnotation("Npgsql:Enum:email_log_status", "sent,failed,pending")
                .OldAnnotation("Npgsql:Enum:employment_type", "full_time,part_time,contract,freelance")
                .OldAnnotation("Npgsql:Enum:interview_session_status", "in_progress,completed,cancelled")
                .OldAnnotation("Npgsql:Enum:job_status", "draft,pending_review,published,rejected,expired,closed")
                .OldAnnotation("Npgsql:Enum:job_type", "full_time,part_time,contract,freelance,internship")
                .OldAnnotation("Npgsql:Enum:notification_type", "system,application,interview,payment,promotion")
                .OldAnnotation("Npgsql:Enum:payment_gateway", "vnpay,momo,stripe,paypal,bank_transfer")
                .OldAnnotation("Npgsql:Enum:payment_status", "pending,success,failed,refunded")
                .OldAnnotation("Npgsql:Enum:payment_target_type", "subscription,wallet_topup,job_promotion")
                .OldAnnotation("Npgsql:Enum:promotion_status", "active,expired,cancelled")
                .OldAnnotation("Npgsql:Enum:review_status", "pending,approved,rejected")
                .OldAnnotation("Npgsql:Enum:skill_status", "active,deactive")
                .OldAnnotation("Npgsql:Enum:subscription_status", "active,inactive")
                .OldAnnotation("Npgsql:Enum:user_status", "active,inactive,banned,pending_verification")
                .OldAnnotation("Npgsql:Enum:user_subscription_status", "active,expired,cancelled");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:Enum:activity_log_category", "auth,system,data_mutation,security")
                .Annotation("Npgsql:Enum:activity_log_status", "success,fail")
                .Annotation("Npgsql:Enum:application_status", "applied,viewed,shortlisted,interviewing,offered,hired,rejected,withdrawn")
                .Annotation("Npgsql:Enum:company_status", "pending,verified,rejected")
                .Annotation("Npgsql:Enum:company_verification_method", "business_registration,poa_and_id")
                .Annotation("Npgsql:Enum:credit_transaction_type", "topup,deduct,refund,bonus")
                .Annotation("Npgsql:Enum:difficulty_level", "easy,medium,hard")
                .Annotation("Npgsql:Enum:email_log_status", "sent,failed,pending")
                .Annotation("Npgsql:Enum:employment_type", "full_time,part_time,contract,freelance")
                .Annotation("Npgsql:Enum:interview_session_status", "in_progress,completed,cancelled")
                .Annotation("Npgsql:Enum:job_status", "draft,pending_review,published,rejected,expired,closed")
                .Annotation("Npgsql:Enum:job_type", "full_time,part_time,contract,freelance,internship")
                .Annotation("Npgsql:Enum:notification_type", "system,application,interview,payment,promotion")
                .Annotation("Npgsql:Enum:payment_gateway", "vnpay,momo,stripe,paypal,bank_transfer")
                .Annotation("Npgsql:Enum:payment_status", "pending,success,failed,refunded")
                .Annotation("Npgsql:Enum:payment_target_type", "subscription,wallet_topup,job_promotion")
                .Annotation("Npgsql:Enum:promotion_status", "active,expired,cancelled")
                .Annotation("Npgsql:Enum:review_status", "pending,approved,rejected")
                .Annotation("Npgsql:Enum:skill_status", "active,deactive")
                .Annotation("Npgsql:Enum:subscription_status", "active,inactive")
                .Annotation("Npgsql:Enum:user_status", "active,inactive,banned,pending_verification")
                .Annotation("Npgsql:Enum:user_subscription_status", "active,expired,cancelled")
                .OldAnnotation("Npgsql:Enum:activity_log_category", "auth,system,data_mutation,security")
                .OldAnnotation("Npgsql:Enum:activity_log_status", "success,fail")
                .OldAnnotation("Npgsql:Enum:application_status", "applied,viewed,shortlisted,interviewing,offered,hired,rejected,withdrawn")
                .OldAnnotation("Npgsql:Enum:company_status", "draft,pending,verified,rejected")
                .OldAnnotation("Npgsql:Enum:company_verification_method", "business_registration,poa_and_id")
                .OldAnnotation("Npgsql:Enum:credit_transaction_type", "topup,deduct,refund,bonus")
                .OldAnnotation("Npgsql:Enum:difficulty_level", "easy,medium,hard")
                .OldAnnotation("Npgsql:Enum:email_log_status", "sent,failed,pending")
                .OldAnnotation("Npgsql:Enum:employment_type", "full_time,part_time,contract,freelance")
                .OldAnnotation("Npgsql:Enum:interview_session_status", "in_progress,completed,cancelled")
                .OldAnnotation("Npgsql:Enum:job_status", "draft,pending_review,published,rejected,expired,closed")
                .OldAnnotation("Npgsql:Enum:job_type", "full_time,part_time,contract,freelance,internship")
                .OldAnnotation("Npgsql:Enum:notification_type", "system,application,interview,payment,promotion")
                .OldAnnotation("Npgsql:Enum:payment_gateway", "vnpay,momo,stripe,paypal,bank_transfer")
                .OldAnnotation("Npgsql:Enum:payment_status", "pending,success,failed,refunded")
                .OldAnnotation("Npgsql:Enum:payment_target_type", "subscription,wallet_topup,job_promotion")
                .OldAnnotation("Npgsql:Enum:promotion_status", "active,expired,cancelled")
                .OldAnnotation("Npgsql:Enum:review_status", "pending,approved,rejected")
                .OldAnnotation("Npgsql:Enum:skill_status", "active,deactive")
                .OldAnnotation("Npgsql:Enum:subscription_status", "active,inactive")
                .OldAnnotation("Npgsql:Enum:user_status", "active,inactive,banned,pending_verification")
                .OldAnnotation("Npgsql:Enum:user_subscription_status", "active,expired,cancelled");
        }
    }
}
