const fs = require('fs');
const en = JSON.parse(fs.readFileSync('messages/en.json', 'utf8'));
const vi = JSON.parse(fs.readFileSync('messages/vi.json', 'utf8'));

const promptsEn = {
  title: 'Prompt Management',
  desc: 'Manage system prompts, AI configurations, and switch active versions across LLM services.',
  searchPlaceholder: 'Search by prompt key, description...',
  clearSearch: 'Clear search',
  clearFilters: 'Clear Filters',
  colPromptKey: 'PROMPT KEY & DESCRIPTION',
  colActiveVersion: 'ACTIVE VERSION',
  colUpdatedAt: 'LAST UPDATED',
  colActions: 'ACTIONS',
  noActiveVersion: 'No Active Version',
  manageBtn: 'Manage',
  loadFailTitle: 'Failed to load system prompts',
  loadFailDesc: 'An error occurred while fetching prompt data. Please try again.',
  noPromptsTitle: 'No system prompts found',
  noPromptsFilterDesc: 'No prompts match the current search query. Try clearing your search.',
  noPromptsEmptyDesc: 'No system prompts available.',
  showingText: 'Showing <span className="font-semibold text-[#050505] dark:text-zinc-200">{start} - {end}</span> of <span className="font-semibold text-[#050505] dark:text-zinc-200">{total}</span> system prompts',
  pageSize: 'Page size',

  versionTagRequired: 'Version Tag is required',
  contentRequired: 'Prompt content is required',
  activateConfirm: 'Are you sure you want to make this version active? The current active version will be deactivated.',
  copySuccess: 'Copied content to new version form',
  loadingDetails: 'Loading prompt details...',
  failedLoadDetail: 'Failed to load prompt',
  noDesc: 'No description provided',
  tabHistory: 'Version History',
  tabCreate: 'Create New Version',
  versionsTitle: 'Versions',
  noVersions: 'No versions found.',
  activeBadge: 'Active',
  createdAt: 'Created at ',
  copyToNewBtn: 'Copy to New',
  activateBtn: 'Activate',
  promptContentTitle: 'Prompt Content',
  modelConfigTitle: 'Model Config (JSON)',
  selectToView: 'Select a version from the left to view details.',
  createTitle: 'Create New Version',
  createDesc: 'Create a new immutable version for <span className="font-mono text-primary">{promptKey}</span>. Remember to keep required placeholders like [CV_TEXT] and [JD_TEXT].',
  versionTagLabel: 'Version Tag',
  versionTagPlaceholder: 'e.g., v2.0-experimental',
  versionTagHelp: 'A unique identifier for this version.',
  draftHelp: 'This version is saved as a draft. Activate it from the analysis prompt-pair card with a compatible counterpart.',
  setActiveLabel: 'Set as Active',
  setActiveHelp: 'Make this version active immediately after creation.',
  promptContentPlaceholder: 'You are an expert recruiter...',
  promptContentHelp: 'Use raw text. Make sure to include variables wrapped in brackets, like [CV_TEXT].',
  modelConfigLabel: 'Model Configuration (Optional JSON)',
  modelConfigHelp: 'Optional JSON overriding default LLM settings. Must be valid JSON.',
  cancelBtn: 'Cancel',
  saveBtn: 'Save Version'
};

const promptsVi = {
  title: 'Quản Lý Prompt',
  desc: 'Quản lý system prompt, cấu hình AI, và chuyển đổi phiên bản hoạt động giữa các dịch vụ LLM.',
  searchPlaceholder: 'Tìm kiếm theo từ khóa prompt, mô tả...',
  clearSearch: 'Xóa tìm kiếm',
  clearFilters: 'Xóa Bộ Lọc',
  colPromptKey: 'TỪ KHÓA & MÔ TẢ PROMPT',
  colActiveVersion: 'PHIÊN BẢN HOẠT ĐỘNG',
  colUpdatedAt: 'CẬP NHẬT LẦN CUỐI',
  colActions: 'THAO TÁC',
  noActiveVersion: 'Không có bản hoạt động',
  manageBtn: 'Quản lý',
  loadFailTitle: 'Tải danh sách system prompt thất bại',
  loadFailDesc: 'Đã xảy ra lỗi khi lấy dữ liệu prompt. Vui lòng thử lại.',
  noPromptsTitle: 'Không tìm thấy system prompt nào',
  noPromptsFilterDesc: 'Không có prompt nào khớp với từ khóa tìm kiếm. Vui lòng thử xóa bộ lọc.',
  noPromptsEmptyDesc: 'Không có system prompt nào khả dụng.',
  showingText: 'Hiển thị <span className="font-semibold text-[#050505] dark:text-zinc-200">{start} - {end}</span> trên tổng số <span className="font-semibold text-[#050505] dark:text-zinc-200">{total}</span> system prompt',
  pageSize: 'Số dòng',

  versionTagRequired: 'Vui lòng nhập Phiên bản',
  contentRequired: 'Vui lòng nhập Nội dung prompt',
  activateConfirm: 'Bạn có chắc chắn muốn kích hoạt phiên bản này? Phiên bản đang hoạt động hiện tại sẽ bị hủy kích hoạt.',
  copySuccess: 'Đã sao chép nội dung vào biểu mẫu tạo mới',
  loadingDetails: 'Đang tải chi tiết prompt...',
  failedLoadDetail: 'Tải thông tin prompt thất bại',
  noDesc: 'Chưa có mô tả',
  tabHistory: 'Lịch sử Phiên bản',
  tabCreate: 'Tạo Phiên bản Mới',
  versionsTitle: 'Các Phiên bản',
  noVersions: 'Không tìm thấy phiên bản nào.',
  activeBadge: 'Đang hoạt động',
  createdAt: 'Tạo lúc ',
  copyToNewBtn: 'Sao chép & Tạo mới',
  activateBtn: 'Kích hoạt',
  promptContentTitle: 'Nội dung Prompt',
  modelConfigTitle: 'Cấu hình Model (JSON)',
  selectToView: 'Chọn một phiên bản bên trái để xem chi tiết.',
  createTitle: 'Tạo Phiên bản Mới',
  createDesc: 'Tạo một phiên bản bất biến mới cho <span className="font-mono text-primary">{promptKey}</span>. Hãy nhớ giữ lại các biến bắt buộc như [CV_TEXT] và [JD_TEXT].',
  versionTagLabel: 'Tên Phiên bản',
  versionTagPlaceholder: 'vd: v2.0-experimental',
  versionTagHelp: 'Một mã định danh duy nhất cho phiên bản này.',
  draftHelp: 'Phiên bản này được lưu dưới dạng nháp. Hãy kích hoạt nó từ thẻ ghép cặp prompt phân tích cùng với một phiên bản đối tác tương thích.',
  setActiveLabel: 'Đặt làm Hoạt động',
  setActiveHelp: 'Làm cho phiên bản này hoạt động ngay sau khi tạo.',
  promptContentPlaceholder: 'Bạn là một chuyên gia tuyển dụng...',
  promptContentHelp: 'Sử dụng văn bản thô. Đảm bảo bao gồm các biến được bọc trong ngoặc vuông, như [CV_TEXT].',
  modelConfigLabel: 'Cấu hình Model (JSON tùy chọn)',
  modelConfigHelp: 'JSON tùy chọn để ghi đè cài đặt LLM mặc định. Phải là JSON hợp lệ.',
  cancelBtn: 'Hủy',
  saveBtn: 'Lưu Phiên bản'
};

en['AdminPrompts'] = promptsEn;
en['StaffPrompts'] = promptsEn;
vi['AdminPrompts'] = promptsVi;
vi['StaffPrompts'] = promptsVi;

fs.writeFileSync('messages/en.json', JSON.stringify(en, null, 2));
fs.writeFileSync('messages/vi.json', JSON.stringify(vi, null, 2));
console.log('Messages updated successfully!');
