const fs = require('fs');

const en = JSON.parse(fs.readFileSync('messages/en.json', 'utf8'));
const vi = JSON.parse(fs.readFileSync('messages/vi.json', 'utf8'));

const masterDataEn = {
  // Shared
  addBtn: 'Add',
  editBtn: 'Edit',
  deleteBtn: 'Delete',
  cancelBtn: 'Cancel',
  saveBtn: 'Save',
  searchPlaceholder: 'Search...',
  resetFilters: 'Reset Filters',
  statusActive: 'Active',
  statusInactive: 'Inactive',
  retryLoading: 'Retry Loading',
  level1: 'Level 1',
  level2: 'Level 2',
  level3: 'Level 3',
  clearFilters: 'Clear Filters',
  
  // Majors
  majorsTitle: 'Major Management',
  majorsDesc: 'Manage academic majors and fields of study.',
  addMajor: 'Add Major',
  editMajor: 'Edit Major',
  deleteMajor: 'Delete Major',
  majorName: 'Major Name',
  majorCode: 'Major Code',
  parentMajor: 'Parent Major',
  majorLevel: 'Level',
  colMajorCode: 'MAJOR CODE',
  colMajorName: 'MAJOR NAME',
  colMajorLevel: 'LEVEL',
  colMajorStatus: 'STATUS',
  colActions: 'ACTIONS',
  noMajorsFound: 'No majors found',
  noMajorsFoundDesc: 'No majors match the current filters. Try clearing or adjusting your filter.',
  majorLoadFailTitle: 'Failed to load majors',
  majorLoadFailDesc: 'An error occurred while fetching major records. Please try again.',
  majorDeleteBlockedTitle: 'Deletion Blocked',
  majorDeleteBlockedDesc: 'You cannot delete specialization "{name}" because it contains active sub-specializations (children). The database enforces restrict deletion to keep parent-child structure valid.',
  activeSubSpecializations: 'Active Sub-Specializations ({count})',
  deleteMajorConfirmTitle: 'Confirm Soft Deletion',
  deleteMajorConfirmDesc: 'Are you sure you want to delete specialization "{name}"? The record is marked as deleted but retained in the database for candidate data integrity.',
  deleteMajorBtn: 'Yes, Delete Specialization',
  toastMajorDeleteSuccess: 'Soft deleted specialization "{name}".',
  toastMajorDeleteError: 'Cannot delete this specialization due to active references or candidate enrollments.',
  majorFormCodeLabel: 'Major Code',
  majorFormCodeDesc: 'A unique code identifying the major (e.g., IT, CS).',
  majorFormNameLabel: 'Major Name',
  majorFormNameDesc: 'The full name of the major.',
  majorFormParentLabel: 'Parent Major (Optional)',
  majorFormParentDesc: 'Select a parent major if this is a sub-specialization.',
  majorFormNoneParent: 'None (Top Level)',
  majorFormSaving: 'Saving...',
  
  // Skills
  skillsTitle: 'Skill Management',
  skillsDesc: 'Manage technical skills, soft skills, and skill categories.',
  addSkill: 'Add Skill',
  editSkill: 'Edit Skill',
  deleteSkill: 'Delete Skill',
  addCategory: 'Add Category',
  editCategory: 'Edit Category',
  deleteCategory: 'Delete Category',
  categoryFormName: 'Category Name',
  categoryFormNamePlaceholder: 'e.g. Programming Languages...',
  categoryDeleteConfirmTitle: 'Confirm Deletion',
  categoryDeleteConfirmDesc: 'Are you sure you want to delete the category "{name}"?',
  categoryDeleteWarning: 'Skills belonging to this category will become "Uncategorized".',
  categoryDeleteBtn: 'Yes, Delete',
  skillFormName: 'Skill Name',
  skillFormNamePlaceholder: 'Enter skill name (e.g. React, .NET Core...)',
  skillFormCategory: 'Category',
  skillFormCategoryPlaceholder: 'Select skill category',
  skillFormAliases: 'Aliases / Synonyms',
  skillFormAliasesPlaceholder: 'e.g. ReactJS, React.js (Press Enter to add)',
  skillFormAliasesDesc: 'Type a synonym or misspelling of this skill and press Enter to add.',
  skillFormStatus: 'Status',
  skillFormActive: 'Active',
  skillFormDisabled: 'Disabled',
  skillDeleteConfirmTitle: 'Confirm Deletion',
  skillDeleteConfirmDesc: 'Are you sure you want to delete the skill "{name}"?',
  skillDeleteBtn: 'Yes, Delete',
  skillForceStatusTitle: 'Force Status Update',
  skillForceStatusDesc: 'The system detected that this skill is currently tied to active candidate profiles or job requirements.',
  skillForceStatusWarning: 'Changing its status might affect matching algorithms. Do you want to proceed and force the update?',
  skillForceStatusNote: '* When disabled, this skill will be hidden and cannot be searched by new candidates or job postings.',
  skillForceStatusBtn: 'Agree to Disable',
  colSkillName: 'SKILL NAME',
  colCategory: 'CATEGORY',
  colType: 'TYPE',
  colStatus: 'STATUS',
  colActions: 'ACTIONS',
  toastCategoryDeleteSuccess: 'Deleted skill category "{name}" successfully.',
  toastSkillDeleteSuccess: 'Deleted skill "{name}" successfully.',
  
  // SFIA Skills
  sfiaTitle: 'SFIA Skill Management',
  sfiaDesc: 'Manage SFIA skills and competency levels.',
  addSfiaSkill: 'Add SFIA Skill',
  importSfiaBtn: 'Import CSV',
  colSfiaCode: 'SFIA CODE',
  colSfiaName: 'SKILL NAME',
  colSfiaCategory: 'CATEGORY',
  sfiaTitle: 'SFIA 9 Skills Framework',
  sfiaDesc: 'Manage standard SFIA 9 skills taxonomy and responsibility level mappings across target roles.',
  sfiaSearchPlaceholder: 'Search by code, name, category, or subcategory...',
  sfiaTotal: 'Total: {count} SFIA skills',
  importCsvBtn: 'Import CSV',
  addSfiaSkillBtn: 'Add SFIA Skill',
  colSfiaSubcategory: 'SUBCATEGORY',
  colSfiaSkillCode: 'SKILL & CODE',
  colSfiaLevels: 'LEVELS (1 - 7)',
  colSfiaActions: 'ACTIONS',
  sfiaEditSkill: 'Edit SFIA Skill',
  sfiaDeleteSkill: 'Delete SFIA Skill',
  sfiaFormTitleCreate: 'Add SFIA Skill',
  sfiaFormTitleEdit: 'Edit SFIA Skill',
  sfiaFormCode: 'Skill Code',
  sfiaFormName: 'Skill Name',
  sfiaFormCategory: 'Category',
  sfiaFormSubcategory: 'Subcategory',
  sfiaFormDesc: 'Description',
  sfiaFormLevels: 'Available Levels',
  sfiaFormLevelDesc: 'Level Descriptions',
  importSfiaTitle: 'Import SFIA Skills (CSV)',
  importSfiaDesc: 'Upload a CSV file containing SFIA skills data to bulk import into the system.',
  importSfiaTemplateBtn: 'Download Template',
  importSfiaClickToUpload: 'Click to upload',
  importSfiaDragAndDrop: 'or drag and drop',
  importSfiaFileHint: 'CSV files only (max 5MB)',
  importSfiaSelectedFile: 'Selected file:',
  importSfiaProcessBtn: 'Process Import',
  
  // Target Roles
  targetRolesTitle: 'Target Role Management',
  targetRolesDesc: 'Manage target roles for career paths.',
  addTargetRole: 'Add Target Role',
  importTargetRoleBtn: 'Import CSV',
  colRoleName: 'ROLE NAME',
  colRoleNameVi: 'ROLE NAME (VI)',
  targetRolesTitle2: 'Target Roles (Templates)',
  targetRolesDesc2: 'Manage standard target role templates and required skill mappings across the platform.',
  targetRolesSearchPlaceholder: 'Search target roles by name or description...',
  addTargetRoleBtn: 'Add new template',
  colTargetRoleName: 'ROLE NAME',
  colTargetRoleType: 'JOB TYPE',
  colTargetRoleLevel: 'JOB LEVEL',
  colTargetRoleSkills: 'REQUIRED SKILLS',
  colTargetRoleActions: 'ACTIONS',
  targetRoleEdit: 'Edit Template',
  targetRoleDelete: 'Delete Template',
  targetRoleFormTitleCreate: 'Add Target Role Template',
  targetRoleFormTitleEdit: 'Edit Target Role Template',
  targetRoleFormNameVi: 'Role Name (Vietnamese)',
  targetRoleFormNameEn: 'Role Name (English)',
  targetRoleFormType: 'Job Type',
  targetRoleFormLevel: 'Job Level',
  targetRoleFormDescVi: 'Description (Vietnamese)',
  targetRoleFormDescEn: 'Description (English)',
  targetRoleFormRequiredSkills: 'Required Skills (SFIA 9)',
  targetRoleFormNoSkills: 'No skills added yet. Search and select skills to add.',
  targetRoleFormSelectSkill: 'Select Skill',
  targetRoleFormRequiredLevel: 'Required Level',
  targetRoleFormNote: 'Note (Optional)',
  targetRoleFormSelectLevel: 'Select Level',
  importTargetRolesTitle: 'Import Target Roles (CSV)',
  importTargetRolesDesc: 'Upload a CSV file containing target role data to bulk import into the system.',
  importTargetRolesTemplateBtn: 'Download Template',
  importTargetRolesClickToUpload: 'Click to upload',
  importTargetRolesDragAndDrop: 'or drag and drop',
  importTargetRolesFileHint: 'CSV files only (max 5MB)',
  importTargetRolesSelectedFile: 'Selected file:',
  importTargetRolesProcessBtn: 'Process Import',
  targetRoleDeleteConfirmTitle: 'Delete Target Role Template?',
  targetRoleDeleteConfirmDesc: 'This action will permanently delete the target role template "{name}" from the database. This action cannot be undone.',
};

const masterDataVi = {
  // Shared
  addBtn: 'Thêm',
  editBtn: 'Sửa',
  deleteBtn: 'Xóa',
  cancelBtn: 'Hủy',
  saveBtn: 'Lưu',
  searchPlaceholder: 'Tìm kiếm...',
  resetFilters: 'Xóa bộ lọc',
  statusActive: 'Đang hoạt động',
  statusInactive: 'Ngừng hoạt động',
  retryLoading: 'Thử lại',
  level1: 'Cấp 1',
  level2: 'Cấp 2',
  level3: 'Cấp 3',
  clearFilters: 'Xóa bộ lọc',
  
  // Majors
  majorsTitle: 'Quản Lý Ngành Học',
  majorsDesc: 'Quản lý danh sách các ngành và chuyên ngành.',
  addMajor: 'Thêm Ngành',
  editMajor: 'Sửa Ngành',
  deleteMajor: 'Xóa Ngành',
  majorName: 'Tên Ngành',
  majorCode: 'Mã Ngành',
  parentMajor: 'Ngành Cha',
  majorLevel: 'Cấp độ',
  colMajorCode: 'MÃ NGÀNH',
  colMajorName: 'TÊN NGÀNH',
  colMajorLevel: 'CẤP ĐỘ',
  colMajorStatus: 'TRẠNG THÁI',
  colActions: 'THAO TÁC',
  noMajorsFound: 'Không tìm thấy ngành học',
  noMajorsFoundDesc: 'Không có ngành nào khớp với bộ lọc hiện tại. Hãy thử xóa hoặc điều chỉnh bộ lọc.',
  majorLoadFailTitle: 'Tải danh sách ngành thất bại',
  majorLoadFailDesc: 'Đã xảy ra lỗi khi lấy danh sách. Vui lòng thử lại.',
  majorDeleteBlockedTitle: 'Cấm Xóa',
  majorDeleteBlockedDesc: 'Bạn không thể xóa ngành "{name}" vì nó chứa các chuyên ngành con đang hoạt động. Cơ sở dữ liệu bắt buộc giữ nguyên cấu trúc cha-con.',
  activeSubSpecializations: 'Chuyên Ngành Con Đang Hoạt Động ({count})',
  deleteMajorConfirmTitle: 'Xác Nhận Xóa Mềm',
  deleteMajorConfirmDesc: 'Bạn có chắc chắn muốn xóa ngành "{name}"? Dữ liệu sẽ được đánh dấu xóa nhưng vẫn giữ trong cơ sở dữ liệu để đảm bảo tính toàn vẹn thông tin của ứng viên.',
  deleteMajorBtn: 'Vâng, Xóa Ngành',
  toastMajorDeleteSuccess: 'Đã xóa mềm ngành "{name}".',
  toastMajorDeleteError: 'Không thể xóa ngành này do đang có liên kết với dữ liệu ứng viên hoặc tài liệu khác.',
  majorFormCodeLabel: 'Mã Ngành',
  majorFormCodeDesc: 'Mã duy nhất định danh ngành (vd: IT, CS).',
  majorFormNameLabel: 'Tên Ngành',
  majorFormNameDesc: 'Tên đầy đủ của ngành.',
  majorFormParentLabel: 'Ngành Cha (Tùy chọn)',
  majorFormParentDesc: 'Chọn ngành cha nếu đây là một chuyên ngành con.',
  majorFormNoneParent: 'Không có (Cấp cao nhất)',
  majorFormSaving: 'Đang lưu...',
  
  // Skills
  skillsTitle: 'Quản Lý Kỹ Năng',
  skillsDesc: 'Quản lý kỹ năng chuyên môn, kỹ năng mềm và nhóm kỹ năng.',
  addSkill: 'Thêm Kỹ Năng',
  editSkill: 'Sửa Kỹ Năng',
  deleteSkill: 'Xóa Kỹ Năng',
  addCategory: 'Thêm Nhóm Kỹ Năng',
  editCategory: 'Sửa Nhóm',
  deleteCategory: 'Xóa Nhóm',
  categoryFormName: 'Tên Nhóm Kỹ Năng',
  categoryFormNamePlaceholder: 'vd. Ngôn ngữ lập trình...',
  categoryDeleteConfirmTitle: 'Xác Nhận Xóa',
  categoryDeleteConfirmDesc: 'Bạn có chắc chắn muốn xóa nhóm kỹ năng "{name}"?',
  categoryDeleteWarning: 'Các kỹ năng thuộc nhóm này sẽ trở thành "Chưa phân loại".',
  categoryDeleteBtn: 'Vâng, Xóa Nhóm',
  skillFormName: 'Tên Kỹ Năng',
  skillFormNamePlaceholder: 'Nhập tên kỹ năng (vd. React, .NET Core...)',
  skillFormCategory: 'Nhóm Kỹ Năng',
  skillFormCategoryPlaceholder: 'Chọn nhóm kỹ năng',
  skillFormAliases: 'Tên thay thế / Từ đồng nghĩa',
  skillFormAliasesPlaceholder: 'vd. ReactJS, React.js (Nhấn Enter để thêm)',
  skillFormAliasesDesc: 'Gõ từ khóa đồng nghĩa, gõ sai chính tả của kỹ năng này và nhấn Enter để thêm mới.',
  skillFormStatus: 'Trạng thái',
  skillFormActive: 'Hoạt động',
  skillFormDisabled: 'Vô hiệu hóa',
  skillDeleteConfirmTitle: 'Xác Nhận Xóa',
  skillDeleteConfirmDesc: 'Bạn có chắc chắn muốn xóa kỹ năng "{name}"?',
  skillDeleteBtn: 'Vâng, Xóa Kỹ Năng',
  skillForceStatusTitle: 'Bắt Buộc Cập Nhật Trạng Thái',
  skillForceStatusDesc: 'Hệ thống phát hiện kỹ năng này hiện đang được liên kết với hồ sơ ứng viên hoặc yêu cầu công việc đang hoạt động.',
  skillForceStatusWarning: 'Việc thay đổi trạng thái của nó có thể ảnh hưởng đến thuật toán đối sánh. Bạn có muốn tiếp tục và bắt buộc cập nhật không?',
  skillForceStatusNote: '* Khi bị vô hiệu hóa, kỹ năng này sẽ bị ẩn và các ứng viên hoặc tin tuyển dụng mới sẽ không thể tìm kiếm được.',
  skillForceStatusBtn: 'Đồng Ý Vô Hiệu Hóa',
  colSkillName: 'TÊN KỸ NĂNG',
  colCategory: 'NHÓM',
  colType: 'LOẠI',
  colStatus: 'TRẠNG THÁI',
  colActions: 'THAO TÁC',
  toastCategoryDeleteSuccess: 'Đã xóa nhóm kỹ năng "{name}" thành công.',
  toastSkillDeleteSuccess: 'Đã xóa kỹ năng "{name}" thành công.',

  // SFIA Skills
  sfiaTitle: 'Quản Lý Kỹ Năng SFIA',
  sfiaDesc: 'Quản lý các kỹ năng và cấp độ năng lực theo chuẩn SFIA.',
  addSfiaSkill: 'Thêm Kỹ Năng SFIA',
  importSfiaBtn: 'Nhập CSV',
  colSfiaCode: 'MÃ SFIA',
  colSfiaName: 'TÊN KỸ NĂNG',
  colSfiaCategory: 'DANH MỤC',
  sfiaTitle: 'Khung Kỹ Năng SFIA 9',
  sfiaDesc: 'Quản lý phân loại kỹ năng SFIA 9 tiêu chuẩn và ánh xạ mức độ trách nhiệm qua các vai trò mục tiêu.',
  sfiaSearchPlaceholder: 'Tìm kiếm theo mã, tên, danh mục hoặc danh mục phụ...',
  sfiaTotal: 'Tổng cộng: {count} kỹ năng SFIA',
  importCsvBtn: 'Nhập CSV',
  addSfiaSkillBtn: 'Thêm Kỹ Năng SFIA',
  colSfiaCategory: 'DANH MỤC',
  colSfiaSubcategory: 'DANH MỤC PHỤ',
  colSfiaSkillCode: 'KỸ NĂNG & MÃ',
  colSfiaLevels: 'CẤP ĐỘ (1 - 7)',
  colSfiaActions: 'HÀNH ĐỘNG',
  sfiaEditSkill: 'Sửa Kỹ Năng SFIA',
  sfiaDeleteSkill: 'Xóa Kỹ Năng SFIA',
  sfiaFormTitleCreate: 'Thêm Kỹ Năng SFIA',
  sfiaFormTitleEdit: 'Sửa Kỹ Năng SFIA',
  sfiaFormCode: 'Mã Kỹ Năng',
  sfiaFormName: 'Tên Kỹ Năng',
  sfiaFormCategory: 'Danh Mục',
  sfiaFormSubcategory: 'Danh Mục Phụ',
  sfiaFormDesc: 'Mô Tả',
  sfiaFormLevels: 'Các Cấp Độ Khả Dụng',
  sfiaFormLevelDesc: 'Mô Tả Cấp Độ',
  importSfiaTitle: 'Nhập Kỹ Năng SFIA (CSV)',
  importSfiaDesc: 'Tải lên một tệp CSV chứa dữ liệu kỹ năng SFIA để nhập hàng loạt vào hệ thống.',
  importSfiaTemplateBtn: 'Tải Biểu Mẫu',
  importSfiaClickToUpload: 'Nhấn để tải lên',
  importSfiaDragAndDrop: 'hoặc kéo và thả',
  importSfiaFileHint: 'Chỉ chấp nhận tệp CSV (tối đa 5MB)',
  importSfiaSelectedFile: 'Tệp đã chọn:',
  importSfiaProcessBtn: 'Tiến Hành Nhập',
  // Target Roles
  targetRolesTitle: 'Quản Lý Vai Trò Đích',
  targetRolesDesc: 'Quản lý các vai trò đích cho lộ trình nghề nghiệp.',
  addTargetRole: 'Thêm Vai Trò',
  importTargetRoleBtn: 'Nhập CSV',
  colRoleName: 'TÊN VAI TRÒ',
  colRoleNameVi: 'TÊN VAI TRÒ (VI)',
  targetRolesTitle2: 'Vai Trò Đích (Biểu mẫu)',
  targetRolesDesc2: 'Quản lý các biểu mẫu vai trò đích tiêu chuẩn và ánh xạ kỹ năng yêu cầu trên toàn bộ hệ thống.',
  targetRolesSearchPlaceholder: 'Tìm kiếm vai trò đích theo tên hoặc mô tả...',
  addTargetRoleBtn: 'Thêm biểu mẫu mới',
  colTargetRoleName: 'TÊN VAI TRÒ',
  colTargetRoleType: 'LOẠI CÔNG VIỆC',
  colTargetRoleLevel: 'CẤP ĐỘ CÔNG VIỆC',
  colTargetRoleSkills: 'KỸ NĂNG YÊU CẦU',
  colTargetRoleActions: 'HÀNH ĐỘNG',
  targetRoleEdit: 'Sửa Biểu Mẫu',
  targetRoleDelete: 'Xóa Biểu Mẫu',
  targetRoleFormTitleCreate: 'Thêm Biểu Mẫu Vai Trò Đích',
  targetRoleFormTitleEdit: 'Sửa Biểu Mẫu Vai Trò Đích',
  targetRoleFormNameVi: 'Tên Vai Trò (Tiếng Việt)',
  targetRoleFormNameEn: 'Tên Vai Trò (Tiếng Anh)',
  targetRoleFormType: 'Loại Công Việc',
  targetRoleFormLevel: 'Cấp Độ Công Việc',
  targetRoleFormDescVi: 'Mô Tả (Tiếng Việt)',
  targetRoleFormDescEn: 'Mô Tả (Tiếng Anh)',
  targetRoleFormRequiredSkills: 'Kỹ Năng Yêu Cầu (SFIA 9)',
  targetRoleFormNoSkills: 'Chưa có kỹ năng nào được thêm. Tìm kiếm và chọn kỹ năng để thêm.',
  targetRoleFormSelectSkill: 'Chọn Kỹ Năng',
  targetRoleFormRequiredLevel: 'Cấp Độ Yêu Cầu',
  targetRoleFormNote: 'Ghi Chú (Tùy chọn)',
  targetRoleFormSelectLevel: 'Chọn Cấp Độ',
  importTargetRolesTitle: 'Nhập Vai Trò Đích (CSV)',
  importTargetRolesDesc: 'Tải lên một tệp CSV chứa dữ liệu vai trò đích để nhập hàng loạt vào hệ thống.',
  importTargetRolesTemplateBtn: 'Tải Biểu Mẫu',
  importTargetRolesClickToUpload: 'Nhấn để tải lên',
  importTargetRolesDragAndDrop: 'hoặc kéo và thả',
  importTargetRolesFileHint: 'Chỉ chấp nhận tệp CSV (tối đa 5MB)',
  importTargetRolesSelectedFile: 'Tệp đã chọn:',
  importTargetRolesProcessBtn: 'Tiến Hành Nhập',
  targetRoleDeleteConfirmTitle: 'Xóa Biểu Mẫu Vai Trò Đích?',
  targetRoleDeleteConfirmDesc: 'Hành động này sẽ xóa vĩnh viễn biểu mẫu vai trò đích "{name}" khỏi cơ sở dữ liệu. Hành động này không thể hoàn tác.',
};

en['AdminMasterData'] = masterDataEn;
vi['AdminMasterData'] = masterDataVi;

fs.writeFileSync('messages/en.json', JSON.stringify(en, null, 2));
fs.writeFileSync('messages/vi.json', JSON.stringify(vi, null, 2));
console.log('MasterData translations updated successfully!');
